In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('Image Data/Abbott_data.xlsx')
df.rename(columns={'name':'Product Name'},inplace=True)

In [ ]:
mdf = pd.read_excel('c:\\Users\\MICILMEDS\\Downloads\\20250917113501.xlsx')

In [ ]:
mdf.head()

In [ ]:
df_m = mdf[mdf['Product Company'].isin(['Abbott','Abbott Healthcare Private Limited','Abbott Healthcare Private Limited','Abbott India Limited'])]
df_m.drop_duplicates(inplace=True)
df_m.reset_index(drop=True,inplace=True)

In [ ]:
df_m

In [ ]:
df['Test1']=df['Product Name'].str.lower().str.replace('-','').str.replace(',','').str.replace('.','').str.replace('®','').str.replace('™','').str.replace('(','').str.replace(')','').str.replace('/','').str.replace('*','').str.replace('+','').str.replace("'",'').str.replace('"','').str.replace('&','and').str.split(' ').str[0:2].str.join(' ')
df_m['Test1']=df_m['Product Name'].str.lower().str.replace('-','').str.replace(',','').str.replace('.','').str.replace('®','').str.replace('™','').str.replace('(','').str.replace(')','').str.replace('/','').str.replace('*','').str.replace('+','').str.replace("'",'').str.replace('"','').str.replace('&','and').str.split(' ').str[0:2].str.join(' ')

In [ ]:
df

In [60]:
df_test = pd.merge(df,df_m,left_on='Test1',right_on='Test1',how='left')

In [64]:
df_test.drop_duplicates(inplace=True)

In [68]:
df_test.head()

,Product Name_x,image_url,Test1,Product Code,Product Name_y,Product Company,Test2
0,RZOLE 20MG TABLET,https://gargagencypharma.com/wp-content/upload...,rzole 20mg,EMD539305,Rzole 20mg Tablet,Abbott,rzole 20mg
1,ESGIPYRIN SP TABLET,https://gargagencypharma.com/wp-content/upload...,esgipyrin sp,EMD411614,Esgipyrin SP Tablet,Abbott,esgipyrin sp
2,ESGIPYRIN A TABLET,https://gargagencypharma.com/wp-content/upload...,esgipyrin a,NaN,NaN,NaN,NaN
3,CHUPP D ADVANCE 100ML SYRUP,https://gargagencypharma.com/wp-content/upload...,chupp d,NaN,NaN,NaN,NaN
4,LUNABET 30ML LOTION-SPRAY,https://gargagencypharma.com/wp-content/upload...,lunabet 30ml,NaN,NaN,NaN,NaN

In [69]:
df_missing = df_test[df_test['Product Code'].isna()]

In [73]:
df_missing.head()

,Product Name_x,image_url,Test1,Product Code,Product Name_y,Product Company,Test2
2,ESGIPYRIN A TABLET,https://gargagencypharma.com/wp-content/upload...,esgipyrin a,NaN,NaN,NaN,NaN
3,CHUPP D ADVANCE 100ML SYRUP,https://gargagencypharma.com/wp-content/upload...,chupp d,NaN,NaN,NaN,NaN
4,LUNABET 30ML LOTION-SPRAY,https://gargagencypharma.com/wp-content/upload...,lunabet 30ml,NaN,NaN,NaN,NaN
5,LUNABET 30GRM CREAM,https://gargagencypharma.com/wp-content/upload...,lunabet 30grm,NaN,NaN,NaN,NaN
6,LUNABET 10GRM CREAM,https://gargagencypharma.com/wp-content/upload...,lunabet 10grm,NaN,NaN,NaN,NaN