In [1]:

url_list = []
for i in range(1,8):
    url = f"https://www.1mg.com/categories/personal-care-products-18?filter=true&page={i}"
    url_list.append(url)
url_list

['https://www.1mg.com/categories/personal-care-products-18?filter=true&page=1',
 'https://www.1mg.com/categories/personal-care-products-18?filter=true&page=2',
 'https://www.1mg.com/categories/personal-care-products-18?filter=true&page=3',
 'https://www.1mg.com/categories/personal-care-products-18?filter=true&page=4',
 'https://www.1mg.com/categories/personal-care-products-18?filter=true&page=5',
 'https://www.1mg.com/categories/personal-care-products-18?filter=true&page=6',
 'https://www.1mg.com/categories/personal-care-products-18?filter=true&page=7']

In [2]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
import numpy as np
import seaborn as sns

# Initialize empty lists to store scraped data
Name = []    # List to store product names
Sizes = []   # List to store product sizes
MRPs = []    # List to store product maximum retail prices (MRPs)
Prices = []  # List to store product prices
URLs = []    # List to store product URLs

page = 0  # Initialize page number for pagination

# Loop to iterate through multiple pages of the website
while True:
    
    # Define headers for the HTTP request
    header={
        'Origin': 'https://www.1mg.com',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'
    }
    
    # Construct the URL for the current page    

    url = "https://www.1mg.com/categories/personal-care-products-18?filter=true&page=" + str(page)

    # Send an HTTP GET request to the URL with the defined headers
    res = requests.get(url=url, headers=header)
    
    # Check if the page is not found (404 status)
    if res.status_code == 404:
        print("Page not found. Exiting loop.")
        break
    else:
        # Parse the HTML content of the response using BeautifulSoup
        obj = soup(res.content, 'html.parser')
        
        # Find all product boxes on the current page
        Box = obj.find_all('div', {'class': 'style__product-box___liepi'})
        
        # Loop through each product box and extract relevant information
        for i in Box:
            # Extract product name
            name = i.find('div', {'class': 'style__pro-title___2QwJy'})
            if name:
                Name.append(name.text.strip())
            else:
                Name.append(None)
            
            # Extract product size
            size = i.find('div', {'class': 'style__pack-size___2JQG7'})
            if size:
                Sizes.append(size.text.strip())
            else:
                Sizes.append(None)
            
            # Extract product MRP (maximum retail price)
            mrps = i.find('span', {'class': 'style__discount-price___25Bya'})
            if mrps:
                MRPs.append(mrps.text.replace("₹", ""))
            else:
                MRPs.append(None)
            
            # Extract product price
            price = i.find('div', {'class': 'style__price-tag___cOxYc'})
            if price:
                Prices.append(price.text.replace("₹", ""))
            else:
                Prices.append(None)
            
            # Extract product URL
            mg_url = i.find('a', {'class': 'style__product-link___UB_67'})
            if mg_url:
                b = "https://www.1mg.com" + mg_url.get('href')
                URLs.append(b)
            else:
                URLs.append(None)
        # Print progress information for the current page
        print(page,"page=>",end=" ")
    if page == 530:  # Limit to 13 pages for this example:
        break
        
    page+=1 # Move to the next page for scraping
    
    print(len(URLs),end=" ")
    print(len(Prices),end=" ")
    print(len(Sizes),end=" ")
    print(len(MRPs),end=" ")
    print(len(Name))

0 page=> 53 53 53 53 53
1 page=> 106 106 106 106 106
2 page=> 159 159 159 159 159
3 page=> 212 212 212 212 212
4 page=> 265 265 265 265 265
5 page=> 318 318 318 318 318
6 page=> 371 371 371 371 371
7 page=> 424 424 424 424 424
8 page=> 477 477 477 477 477
9 page=> 530 530 530 530 530
10 page=> 583 583 583 583 583
11 page=> 636 636 636 636 636
12 page=> 689 689 689 689 689
13 page=> 742 742 742 742 742
14 page=> 795 795 795 795 795
15 page=> 848 848 848 848 848
16 page=> 901 901 901 901 901
17 page=> 954 954 954 954 954
18 page=> 1007 1007 1007 1007 1007
19 page=> 1060 1060 1060 1060 1060
20 page=> 1113 1113 1113 1113 1113
21 page=> 1166 1166 1166 1166 1166
22 page=> 1219 1219 1219 1219 1219
23 page=> 1272 1272 1272 1272 1272
24 page=> 1325 1325 1325 1325 1325
25 page=> 1378 1378 1378 1378 1378
26 page=> 1431 1431 1431 1431 1431
27 page=> 1484 1484 1484 1484 1484
28 page=> 1537 1537 1537 1537 1537
29 page=> 1590 1590 1590 1590 1590
30 page=> 1643 1643 1643 1643 1643
31 page=> 1696 1696 1696 1696 1696
32 page=> 1749 1749 1749 1749 1749
33 page=> 1802 1802 1802 1802 1802
34 page=> 1855 1855 1855 1855 1855
35 page=> 1908 1908 1908 1908 1908
36 page=> 1961 1961 1961 1961 1961
37 page=> 2014 2014 2014 2014 2014
38 page=> 2067 2067 2067 2067 2067
39 page=> 2120 2120 2120 2120 2120
40 page=> 2173 2173 2173 2173 2173
41 page=> 2226 2226 2226 2226 2226
42 page=> 2279 2279 2279 2279 2279
43 page=> 2332 2332 2332 2332 2332
44 page=> 2385 2385 2385 2385 2385
45 page=> 2438 2438 2438 2438 2438
46 page=> 2491 2491 2491 2491 2491
47 page=> 2544 2544 2544 2544 2544
48 page=> 2597 2597 2597 2597 2597
49 page=> 2650 2650 2650 2650 2650
50 page=> 2703 2703 2703 2703 2703
51 page=> 2756 2756 2756 2756 2756
52 page=> 2809 2809 2809 2809 2809
53 page=> 2862 2862 2862 2862 2862
54 page=> 2915 2915 2915 2915 2915
55 page=> 2968 2968 2968 2968 2968
56 page=> 3021 3021 3021 3021 3021
57 page=> 3074 3074 3074 3074 3074
58 page=> 3127 3127 3127 3127 3127
59 page=> 3180 3180 3180 3180 3180
60 page=> 3233 3233 3233 3233 3233
61 page=> 3286 3286 3286 3286 3286
62 page=> 3339 3339 3339 3339 3339
63 page=> 3392 3392 3392 3392 3392
64 page=> 3445 3445 3445 3445 3445
65 page=> 3498 3498 3498 3498 3498
66 page=> 3551 3551 3551 3551 3551
67 page=> 3604 3604 3604 3604 3604
68 page=> 3657 3657 3657 3657 3657
69 page=> 3710 3710 3710 3710 3710
70 page=> 3763 3763 3763 3763 3763
71 page=> 3816 3816 3816 3816 3816
72 page=> 3869 3869 3869 3869 3869
73 page=> 3922 3922 3922 3922 3922
74 page=> 3975 3975 3975 3975 3975
75 page=> 4028 4028 4028 4028 4028
76 page=> 4081 4081 4081 4081 4081
77 page=> 4134 4134 4134 4134 4134
78 page=> 4187 4187 4187 4187 4187
79 page=> 4240 4240 4240 4240 4240
80 page=> 4293 4293 4293 4293 4293
81 page=> 4346 4346 4346 4346 4346
82 page=> 4399 4399 4399 4399 4399
83 page=> 4452 4452 4452 4452 4452
84 page=> 4505 4505 4505 4505 4505
85 page=> 4558 4558 4558 4558 4558
86 page=> 4611 4611 4611 4611 4611
87 page=> 4664 4664 4664 4664 4664
88 page=> 4717 4717 4717 4717 4717
89 page=> 4770 4770 4770 4770 4770
90 page=> 4823 4823 4823 4823 4823
91 page=> 4876 4876 4876 4876 4876
92 page=> 4929 4929 4929 4929 4929
93 page=> 4982 4982 4982 4982 4982
94 page=> 5035 5035 5035 5035 5035
95 page=> 5088 5088 5088 5088 5088
96 page=> 5141 5141 5141 5141 5141
97 page=> 5194 5194 5194 5194 5194
98 page=> 5247 5247 5247 5247 5247
99 page=> 5300 5300 5300 5300 5300
100 page=> 5353 5353 5353 5353 5353
101 page=> 5406 5406 5406 5406 5406
102 page=> 5459 5459 5459 5459 5459
103 page=> 5512 5512 5512 5512 5512
104 page=> 5565 5565 5565 5565 5565
105 page=> 5618 5618 5618 5618 5618
106 page=> 5671 5671 5671 5671 5671
107 page=> 5724 5724 5724 5724 5724
108 page=> 5777 5777 5777 5777 5777
109 page=> 5830 5830 5830 5830 5830
110 page=> 5883 5883 5883 5883 5883
111 page=> 5936 5936 5936 5936 5936
112 page=> 5989 5989 5989 5989 5989
113 page=> 6042 6042 6042 6042 6042
114 page=> 6095 6095 6095 6095 6095
115 page=> 6148 6148 6148 6148 6148
116 page=> 6201 6201 6201 6201 6201
117 page=> 6254 6254 6254 6254 6254
118 page=> 6307 6307 6307 6307 6307
119 page=> 6360 6360 6360 6360 6360
120 page=> 6413 6413 6413 6413 6413
121 page=> 6466 6466 6466 6466 6466
122 page=> 6519 6519 6519 6519 6519
123 page=> 6572 6572 6572 6572 6572
124 page=> 6625 6625 6625 6625 6625
125 page=> 6678 6678 6678 6678 6678
126 page=> 6731 6731 6731 6731 6731
127 page=> 6784 6784 6784 6784 6784
128 page=> 6837 6837 6837 6837 6837
129 page=> 6890 6890 6890 6890 6890
130 page=> 6943 6943 6943 6943 6943
131 page=> 6996 6996 6996 6996 6996
132 page=> 7049 7049 7049 7049 7049
133 page=> 7102 7102 7102 7102 7102
134 page=> 7155 7155 7155 7155 7155
135 page=> 7208 7208 7208 7208 7208
136 page=> 7261 7261 7261 7261 7261
137 page=> 7314 7314 7314 7314 7314
138 page=> 7367 7367 7367 7367 7367
139 page=> 7420 7420 7420 7420 7420
140 page=> 7473 7473 7473 7473 7473
141 page=> 7526 7526 7526 7526 7526
142 page=> 7579 7579 7579 7579 7579
143 page=> 7632 7632 7632 7632 7632
144 page=> 7685 7685 7685 7685 7685
145 page=> 7738 7738 7738 7738 7738
146 page=> 7791 7791 7791 7791 7791
147 page=> 7844 7844 7844 7844 7844
148 page=> 7897 7897 7897 7897 7897
149 page=> 7950 7950 7950 7950 7950
150 page=> 8003 8003 8003 8003 8003
151 page=> 8056 8056 8056 8056 8056
152 page=> 8109 8109 8109 8109 8109
153 page=> 8162 8162 8162 8162 8162
154 page=> 8215 8215 8215 8215 8215
155 page=> 8268 8268 8268 8268 8268
156 page=> 8321 8321 8321 8321 8321
157 page=> 8374 8374 8374 8374 8374
158 page=> 8427 8427 8427 8427 8427
159 page=> 8480 8480 8480 8480 8480
160 page=> 8533 8533 8533 8533 8533
161 page=> 8586 8586 8586 8586 8586
162 page=> 8639 8639 8639 8639 8639
163 page=> 8692 8692 8692 8692 8692
164 page=> 8745 8745 8745 8745 8745
165 page=> 8798 8798 8798 8798 8798
166 page=> 8851 8851 8851 8851 8851
167 page=> 8904 8904 8904 8904 8904
168 page=> 8957 8957 8957 8957 8957
169 page=> 9010 9010 9010 9010 9010
170 page=> 9063 9063 9063 9063 9063
171 page=> 9116 9116 9116 9116 9116
172 page=> 9169 9169 9169 9169 9169
173 page=> 9222 9222 9222 9222 9222
174 page=> 9275 9275 9275 9275 9275
175 page=> 9328 9328 9328 9328 9328
176 page=> 9381 9381 9381 9381 9381
177 page=> 9434 9434 9434 9434 9434
178 page=> 9487 9487 9487 9487 9487
179 page=> 9540 9540 9540 9540 9540
180 page=> 9593 9593 9593 9593 9593
181 page=> 9646 9646 9646 9646 9646
182 page=> 9699 9699 9699 9699 9699
183 page=> 9752 9752 9752 9752 9752
184 page=> 9805 9805 9805 9805 9805
185 page=> 9858 9858 9858 9858 9858
186 page=> 9911 9911 9911 9911 9911
187 page=> 9964 9964 9964 9964 9964
188 page=> 10017 10017 10017 10017 10017
189 page=> 10070 10070 10070 10070 10070
190 page=> 10123 10123 10123 10123 10123
191 page=> 10176 10176 10176 10176 10176
192 page=> 10229 10229 10229 10229 10229
193 page=> 10269 10269 10269 10269 10269
194 page=> 10309 10309 10309 10309 10309
195 page=> 10349 10349 10349 10349 10349
196 page=> 10389 10389 10389 10389 10389
197 page=> 10429 10429 10429 10429 10429
198 page=> 10469 10469 10469 10469 10469
199 page=> 10509 10509 10509 10509 10509
200 page=> 10549 10549 10549 10549 10549
201 page=> 10589 10589 10589 10589 10589
202 page=> 10629 10629 10629 10629 10629
203 page=> 10669 10669 10669 10669 10669
204 page=> 10709 10709 10709 10709 10709
205 page=> 10749 10749 10749 10749 10749
206 page=> 10789 10789 10789 10789 10789
207 page=> 10829 10829 10829 10829 10829
208 page=> 10869 10869 10869 10869 10869
209 page=> 10909 10909 10909 10909 10909
210 page=> 10949 10949 10949 10949 10949
211 page=> 10989 10989 10989 10989 10989
212 page=> 11029 11029 11029 11029 11029
213 page=> 11069 11069 11069 11069 11069
214 page=> 11109 11109 11109 11109 11109
215 page=> 11149 11149 11149 11149 11149
216 page=> 11189 11189 11189 11189 11189
217 page=> 11229 11229 11229 11229 11229
218 page=> 11269 11269 11269 11269 11269
219 page=> 11309 11309 11309 11309 11309
220 page=> 11349 11349 11349 11349 11349
221 page=> 11389 11389 11389 11389 11389
222 page=> 11429 11429 11429 11429 11429
223 page=> 11469 11469 11469 11469 11469
224 page=> 11509 11509 11509 11509 11509
225 page=> 11549 11549 11549 11549 11549
226 page=> 11589 11589 11589 11589 11589
227 page=> 11629 11629 11629 11629 11629
228 page=> 11669 11669 11669 11669 11669
229 page=> 11709 11709 11709 11709 11709
230 page=> 11749 11749 11749 11749 11749
231 page=> 11789 11789 11789 11789 11789
232 page=> 11829 11829 11829 11829 11829
233 page=> 11869 11869 11869 11869 11869
234 page=> 11909 11909 11909 11909 11909
235 page=> 11949 11949 11949 11949 11949
236 page=> 11989 11989 11989 11989 11989
237 page=> 12029 12029 12029 12029 12029
238 page=> 12069 12069 12069 12069 12069
239 page=> 12109 12109 12109 12109 12109
240 page=> 12149 12149 12149 12149 12149
241 page=> 12189 12189 12189 12189 12189
242 page=> 12229 12229 12229 12229 12229
243 page=> 12269 12269 12269 12269 12269
244 page=> 12309 12309 12309 12309 12309
245 page=> 12349 12349 12349 12349 12349
246 page=> 12389 12389 12389 12389 12389
247 page=> 12429 12429 12429 12429 12429
248 page=> 12469 12469 12469 12469 12469
249 page=> 12509 12509 12509 12509 12509
250 page=> 12549 12549 12549 12549 12549
251 page=> 12589 12589 12589 12589 12589
252 page=> 12629 12629 12629 12629 12629
253 page=> 12669 12669 12669 12669 12669
254 page=> 12709 12709 12709 12709 12709
255 page=> 12749 12749 12749 12749 12749
256 page=> 12789 12789 12789 12789 12789
257 page=> 12829 12829 12829 12829 12829
258 page=> 12869 12869 12869 12869 12869
259 page=> 12909 12909 12909 12909 12909
260 page=> 12949 12949 12949 12949 12949
261 page=> 12989 12989 12989 12989 12989
262 page=> 13029 13029 13029 13029 13029
263 page=> 13069 13069 13069 13069 13069
264 page=> 13109 13109 13109 13109 13109
265 page=> 13149 13149 13149 13149 13149
266 page=> 13189 13189 13189 13189 13189
267 page=> 13229 13229 13229 13229 13229
268 page=> 13269 13269 13269 13269 13269
269 page=> 13309 13309 13309 13309 13309
270 page=> 13349 13349 13349 13349 13349
271 page=> 13389 13389 13389 13389 13389
272 page=> 13429 13429 13429 13429 13429
273 page=> 13469 13469 13469 13469 13469
274 page=> 13509 13509 13509 13509 13509
275 page=> 13549 13549 13549 13549 13549
276 page=> 13589 13589 13589 13589 13589
277 page=> 13629 13629 13629 13629 13629
278 page=> 13669 13669 13669 13669 13669
279 page=> 13709 13709 13709 13709 13709
280 page=> 13749 13749 13749 13749 13749
281 page=> 13789 13789 13789 13789 13789
282 page=> 13829 13829 13829 13829 13829
283 page=> 13869 13869 13869 13869 13869
284 page=> 13909 13909 13909 13909 13909
285 page=> 13949 13949 13949 13949 13949
286 page=> 13989 13989 13989 13989 13989
287 page=> 14029 14029 14029 14029 14029
288 page=> 14069 14069 14069 14069 14069
289 page=> 14109 14109 14109 14109 14109
290 page=> 14149 14149 14149 14149 14149
291 page=> 14189 14189 14189 14189 14189
292 page=> 14229 14229 14229 14229 14229
293 page=> 14269 14269 14269 14269 14269
294 page=> 14309 14309 14309 14309 14309
295 page=> 14349 14349 14349 14349 14349
296 page=> 14389 14389 14389 14389 14389
297 page=> 14429 14429 14429 14429 14429
298 page=> 14469 14469 14469 14469 14469
299 page=> 14509 14509 14509 14509 14509
300 page=> 14549 14549 14549 14549 14549
301 page=> 14589 14589 14589 14589 14589
302 page=> 14629 14629 14629 14629 14629
303 page=> 14669 14669 14669 14669 14669
304 page=> 14709 14709 14709 14709 14709
305 page=> 14749 14749 14749 14749 14749
306 page=> 14789 14789 14789 14789 14789
307 page=> 14829 14829 14829 14829 14829
308 page=> 14869 14869 14869 14869 14869
309 page=> 14909 14909 14909 14909 14909
310 page=> 14949 14949 14949 14949 14949
311 page=> 14989 14989 14989 14989 14989
312 page=> 15029 15029 15029 15029 15029
313 page=> 15069 15069 15069 15069 15069
314 page=> 15109 15109 15109 15109 15109
315 page=> 15149 15149 15149 15149 15149
316 page=> 15189 15189 15189 15189 15189
317 page=> 15229 15229 15229 15229 15229
318 page=> 15269 15269 15269 15269 15269
319 page=> 15309 15309 15309 15309 15309
320 page=> 15349 15349 15349 15349 15349
321 page=> 15389 15389 15389 15389 15389
322 page=> 15429 15429 15429 15429 15429
323 page=> 15469 15469 15469 15469 15469
324 page=> 15509 15509 15509 15509 15509
325 page=> 15549 15549 15549 15549 15549
326 page=> 15589 15589 15589 15589 15589
327 page=> 15629 15629 15629 15629 15629
328 page=> 15669 15669 15669 15669 15669
329 page=> 15709 15709 15709 15709 15709
330 page=> 15749 15749 15749 15749 15749
331 page=> 15789 15789 15789 15789 15789
332 page=> 15829 15829 15829 15829 15829
333 page=> 15869 15869 15869 15869 15869
334 page=> 15909 15909 15909 15909 15909
335 page=> 15949 15949 15949 15949 15949
336 page=> 15989 15989 15989 15989 15989
337 page=> 16029 16029 16029 16029 16029
338 page=> 16069 16069 16069 16069 16069
339 page=> 16109 16109 16109 16109 16109
340 page=> 16149 16149 16149 16149 16149
341 page=> 16189 16189 16189 16189 16189
342 page=> 16229 16229 16229 16229 16229
343 page=> 16269 16269 16269 16269 16269
344 page=> 16309 16309 16309 16309 16309
345 page=> 16349 16349 16349 16349 16349
346 page=> 16389 16389 16389 16389 16389
347 page=> 16429 16429 16429 16429 16429
348 page=> 16469 16469 16469 16469 16469
349 page=> 16509 16509 16509 16509 16509
350 page=> 16549 16549 16549 16549 16549
351 page=> 16589 16589 16589 16589 16589
352 page=> 16629 16629 16629 16629 16629
353 page=> 16669 16669 16669 16669 16669
354 page=> 16709 16709 16709 16709 16709
355 page=> 16749 16749 16749 16749 16749
356 page=> 16789 16789 16789 16789 16789
357 page=> 16829 16829 16829 16829 16829
358 page=> 16869 16869 16869 16869 16869
359 page=> 16909 16909 16909 16909 16909
360 page=> 16949 16949 16949 16949 16949
361 page=> 16989 16989 16989 16989 16989
362 page=> 17029 17029 17029 17029 17029
363 page=> 17069 17069 17069 17069 17069
364 page=> 17109 17109 17109 17109 17109
365 page=> 17149 17149 17149 17149 17149
366 page=> 17189 17189 17189 17189 17189
367 page=> 17229 17229 17229 17229 17229
368 page=> 17269 17269 17269 17269 17269
369 page=> 17309 17309 17309 17309 17309
370 page=> 17349 17349 17349 17349 17349
371 page=> 17389 17389 17389 17389 17389
372 page=> 17429 17429 17429 17429 17429
373 page=> 17469 17469 17469 17469 17469
374 page=> 17509 17509 17509 17509 17509
375 page=> 17549 17549 17549 17549 17549
376 page=> 17589 17589 17589 17589 17589
377 page=> 17629 17629 17629 17629 17629
378 page=> 17669 17669 17669 17669 17669
379 page=> 17709 17709 17709 17709 17709
380 page=> 17749 17749 17749 17749 17749
381 page=> 17789 17789 17789 17789 17789
382 page=> 17829 17829 17829 17829 17829
383 page=> 17869 17869 17869 17869 17869
384 page=> 17909 17909 17909 17909 17909
385 page=> 17949 17949 17949 17949 17949
386 page=> 17989 17989 17989 17989 17989
387 page=> 18029 18029 18029 18029 18029
388 page=> 18069 18069 18069 18069 18069
389 page=> 18109 18109 18109 18109 18109
390 page=> 18149 18149 18149 18149 18149
391 page=> 18189 18189 18189 18189 18189
392 page=> 18229 18229 18229 18229 18229
393 page=> 18269 18269 18269 18269 18269
394 page=> 18309 18309 18309 18309 18309
395 page=> 18349 18349 18349 18349 18349
396 page=> 18389 18389 18389 18389 18389
397 page=> 18429 18429 18429 18429 18429
398 page=> 18469 18469 18469 18469 18469
399 page=> 18509 18509 18509 18509 18509
400 page=> 18549 18549 18549 18549 18549
401 page=> 18589 18589 18589 18589 18589
402 page=> 18629 18629 18629 18629 18629
403 page=> 18669 18669 18669 18669 18669
404 page=> 18709 18709 18709 18709 18709
405 page=> 18749 18749 18749 18749 18749
406 page=> 18789 18789 18789 18789 18789
407 page=> 18829 18829 18829 18829 18829
408 page=> 18869 18869 18869 18869 18869
409 page=> 18909 18909 18909 18909 18909
410 page=> 18949 18949 18949 18949 18949
411 page=> 18989 18989 18989 18989 18989
412 page=> 19029 19029 19029 19029 19029
413 page=> 19069 19069 19069 19069 19069
414 page=> 19109 19109 19109 19109 19109
415 page=> 19149 19149 19149 19149 19149
416 page=> 19189 19189 19189 19189 19189
417 page=> 19229 19229 19229 19229 19229
418 page=> 19269 19269 19269 19269 19269
419 page=> 19309 19309 19309 19309 19309
420 page=> 19349 19349 19349 19349 19349
421 page=> 19389 19389 19389 19389 19389
422 page=> 19429 19429 19429 19429 19429
423 page=> 19469 19469 19469 19469 19469
424 page=> 19509 19509 19509 19509 19509
425 page=> 19549 19549 19549 19549 19549
426 page=> 19589 19589 19589 19589 19589
427 page=> 19629 19629 19629 19629 19629
428 page=> 19669 19669 19669 19669 19669
429 page=> 19709 19709 19709 19709 19709
430 page=> 19749 19749 19749 19749 19749
431 page=> 19789 19789 19789 19789 19789
432 page=> 19829 19829 19829 19829 19829
433 page=> 19869 19869 19869 19869 19869
434 page=> 19909 19909 19909 19909 19909
435 page=> 19949 19949 19949 19949 19949
436 page=> 19989 19989 19989 19989 19989
437 page=> 20029 20029 20029 20029 20029
438 page=> 20069 20069 20069 20069 20069
439 page=> 20109 20109 20109 20109 20109
440 page=> 20149 20149 20149 20149 20149
441 page=> 20189 20189 20189 20189 20189
442 page=> 20229 20229 20229 20229 20229
443 page=> 20269 20269 20269 20269 20269
444 page=> 20309 20309 20309 20309 20309
445 page=> 20349 20349 20349 20349 20349
446 page=> 20389 20389 20389 20389 20389
447 page=> 20429 20429 20429 20429 20429
448 page=> 20469 20469 20469 20469 20469
449 page=> 20509 20509 20509 20509 20509
450 page=> 20549 20549 20549 20549 20549
451 page=> 20589 20589 20589 20589 20589
452 page=> 20629 20629 20629 20629 20629
453 page=> 20669 20669 20669 20669 20669
454 page=> 20709 20709 20709 20709 20709
455 page=> 20749 20749 20749 20749 20749
456 page=> 20789 20789 20789 20789 20789
457 page=> 20829 20829 20829 20829 20829
458 page=> 20869 20869 20869 20869 20869
459 page=> 20909 20909 20909 20909 20909
460 page=> 20949 20949 20949 20949 20949
461 page=> 20989 20989 20989 20989 20989
462 page=> 21029 21029 21029 21029 21029
463 page=> 21069 21069 21069 21069 21069
464 page=> 21109 21109 21109 21109 21109
465 page=> 21149 21149 21149 21149 21149
466 page=> 21189 21189 21189 21189 21189
467 page=> 21229 21229 21229 21229 21229
468 page=> 21269 21269 21269 21269 21269
469 page=> 21309 21309 21309 21309 21309
470 page=> 21349 21349 21349 21349 21349
471 page=> 21389 21389 21389 21389 21389
472 page=> 21429 21429 21429 21429 21429
473 page=> 21469 21469 21469 21469 21469
474 page=> 21509 21509 21509 21509 21509
475 page=> 21549 21549 21549 21549 21549
476 page=> 21589 21589 21589 21589 21589
477 page=> 21629 21629 21629 21629 21629
478 page=> 21669 21669 21669 21669 21669
479 page=> 21709 21709 21709 21709 21709
480 page=> 21749 21749 21749 21749 21749
481 page=> 21789 21789 21789 21789 21789
482 page=> 21829 21829 21829 21829 21829
483 page=> 21869 21869 21869 21869 21869
484 page=> 21909 21909 21909 21909 21909
485 page=> 21949 21949 21949 21949 21949
486 page=> 21989 21989 21989 21989 21989
487 page=> 22029 22029 22029 22029 22029
488 page=> 22069 22069 22069 22069 22069
489 page=> 22109 22109 22109 22109 22109
490 page=> 22149 22149 22149 22149 22149
491 page=> 22189 22189 22189 22189 22189
492 page=> 22229 22229 22229 22229 22229
493 page=> 22269 22269 22269 22269 22269
494 page=> 22309 22309 22309 22309 22309
495 page=> 22349 22349 22349 22349 22349
496 page=> 22389 22389 22389 22389 22389
497 page=> 22429 22429 22429 22429 22429
498 page=> 22469 22469 22469 22469 22469
499 page=> 22509 22509 22509 22509 22509
500 page=> 22549 22549 22549 22549 22549
501 page=> 22589 22589 22589 22589 22589
502 page=> 22629 22629 22629 22629 22629
503 page=> 22669 22669 22669 22669 22669
504 page=> 22709 22709 22709 22709 22709
505 page=> 22749 22749 22749 22749 22749
506 page=> 22789 22789 22789 22789 22789
507 page=> 22829 22829 22829 22829 22829
508 page=> 22869 22869 22869 22869 22869
509 page=> 22909 22909 22909 22909 22909
510 page=> 22949 22949 22949 22949 22949
511 page=> 22989 22989 22989 22989 22989
512 page=> 23029 23029 23029 23029 23029
513 page=> 23069 23069 23069 23069 23069
514 page=> 23109 23109 23109 23109 23109

In [3]:
data={"name":Name,"size_of_bottle":Sizes,"MRPs":MRPs,"selling_price":Prices,"1mg_url":URLs}

In [4]:
df = pd.DataFrame(data) # Sort the DataFrame by MRPs in descending order
df  # Sort the DataFrame by product name

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Cetaphil Gentle Skin Cleanser | For Dry to Nor...,pump bottle of 1000 ml Cleanser,1679,Discounted Price: 1511,https://www.1mg.com/otc/cetaphil-gentle-skin-c...
1,Sensodyne Repair & Protect Sensitive Toothpaste,tube of 100 gm Toothpaste,270,Discounted Price: 252,https://www.1mg.com/otc/sensodyne-repair-prote...
2,Lacto Calamine Sunscreen | With Kaolin Clay & ...,tube of 50 gm Cream,399,Discounted Price: 219,https://www.1mg.com/otc/lacto-calamine-sunscre...
3,Sesderma Ocean Skin Nourishing Facial Cream,jar of 50 ml Cream,None,MRP3300,https://www.1mg.com/otc/sesderma-ocean-skin-no...
4,Rivela Lite Weightless Mousse Broad Spectrum U...,tube of 40 gm Cream,700,Discounted Price: 617,https://www.1mg.com/otc/rivela-lite-weightless...
...,...,...,...,...,...
23739,Beardhood Beard & Mustache Wax,jar of 30 gm Wax,400,Discounted Price: 289,https://www.1mg.com/otc/beardhood-beard-mustac...
23740,Pores Be Pure Skin Brightening & Exfoliating F...,tube of 100 gm Face Wash,299,Discounted Price: 179,https://www.1mg.com/otc/pores-be-pure-skin-bri...
23741,Himalaya Gentle Baby Wipes,packet of 72 wipes,280,Discounted Price: 263,https://www.1mg.com/otc/himalaya-gentle-baby-w...
23742,Beardhood Clean Look Face Wash,bottle of 100 ml Face Wash,299,Discounted Price: 253,https://www.1mg.com/otc/beardhood-clean-look-f...
23743,Chicco Teat Perfect 5 for Babies 6M+ 6m+,box of 1 Unit,319,Discounted Price: 306,https://www.1mg.com/otc/chicco-teat-perfect-5-...

In [5]:
df['selling_price'] = df['selling_price'].str.replace(r'MRP\s*', '', regex=True)
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Cetaphil Gentle Skin Cleanser | For Dry to Nor...,pump bottle of 1000 ml Cleanser,1679,Discounted Price: 1511,https://www.1mg.com/otc/cetaphil-gentle-skin-c...
1,Sensodyne Repair & Protect Sensitive Toothpaste,tube of 100 gm Toothpaste,270,Discounted Price: 252,https://www.1mg.com/otc/sensodyne-repair-prote...
2,Lacto Calamine Sunscreen | With Kaolin Clay & ...,tube of 50 gm Cream,399,Discounted Price: 219,https://www.1mg.com/otc/lacto-calamine-sunscre...
3,Sesderma Ocean Skin Nourishing Facial Cream,jar of 50 ml Cream,None,3300,https://www.1mg.com/otc/sesderma-ocean-skin-no...
4,Rivela Lite Weightless Mousse Broad Spectrum U...,tube of 40 gm Cream,700,Discounted Price: 617,https://www.1mg.com/otc/rivela-lite-weightless...
...,...,...,...,...,...
23739,Beardhood Beard & Mustache Wax,jar of 30 gm Wax,400,Discounted Price: 289,https://www.1mg.com/otc/beardhood-beard-mustac...
23740,Pores Be Pure Skin Brightening & Exfoliating F...,tube of 100 gm Face Wash,299,Discounted Price: 179,https://www.1mg.com/otc/pores-be-pure-skin-bri...
23741,Himalaya Gentle Baby Wipes,packet of 72 wipes,280,Discounted Price: 263,https://www.1mg.com/otc/himalaya-gentle-baby-w...
23742,Beardhood Clean Look Face Wash,bottle of 100 ml Face Wash,299,Discounted Price: 253,https://www.1mg.com/otc/beardhood-clean-look-f...
23743,Chicco Teat Perfect 5 for Babies 6M+ 6m+,box of 1 Unit,319,Discounted Price: 306,https://www.1mg.com/otc/chicco-teat-perfect-5-...

In [6]:
df['selling_price'] = df['selling_price'].str.replace(r'Discounted Price:\s*', '', regex=True)
df.head(50)

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Cetaphil Gentle Skin Cleanser | For Dry to Nor...,pump bottle of 1000 ml Cleanser,1679,1511,https://www.1mg.com/otc/cetaphil-gentle-skin-c...
1,Sensodyne Repair & Protect Sensitive Toothpaste,tube of 100 gm Toothpaste,270,252,https://www.1mg.com/otc/sensodyne-repair-prote...
2,Lacto Calamine Sunscreen | With Kaolin Clay & ...,tube of 50 gm Cream,399,219,https://www.1mg.com/otc/lacto-calamine-sunscre...
3,Sesderma Ocean Skin Nourishing Facial Cream,jar of 50 ml Cream,None,3300,https://www.1mg.com/otc/sesderma-ocean-skin-no...
4,Rivela Lite Weightless Mousse Broad Spectrum U...,tube of 40 gm Cream,700,617,https://www.1mg.com/otc/rivela-lite-weightless...
5,Cetaphil Oily Skin Cleanser | For Combination ...,bottle of 125 ml Cleanser,699,615,https://www.1mg.com/otc/cetaphil-oily-skin-cle...
6,Minimalist 10% Vitamin C Face Serum | Brighten...,bottle of 30 ml Serum,699,629,https://www.1mg.com/otc/minimalist-10-vitamin-...
7,Hamdard Safi Natural Blood Purifier Syrup | Fo...,bottle of 500 ml Syrup,250,228,https://www.1mg.com/otc/hamdard-safi-natural-b...
8,CIR Adult Diaper Pants | 10 hr Absorption Prot...,packet of 10 diapers,499,233,https://www.1mg.com/otc/cir-adult-diaper-pants...
9,Sesderma Ocean skin Moisturising Serum,bottle of 30 ml Serum,None,2800,https://www.1mg.com/otc/sesderma-ocean-skin-mo...
10,i-Know Ovulation Kit | Testing Strip Kit | Fir...,packet of 5 Test Kits,549,339,https://www.1mg.com/otc/i-know-ovulation-kit-t...
11,Cetaphil Baby Daily Lotion | Nourishes Skin,pump bottle of 400 ml Lotion,950,846,https://www.1mg.com/otc/cetaphil-baby-daily-lo...
12,Minimalist 16% Vitamin C + E + Ferulic Acid Fa...,bottle of 20 ml Serum,599,539,https://www.1mg.com/otc/minimalist-16-vitamin-...
13,Bare Anatomy Anti-Dandruff Shampoo,bottle of 250 ml Shampoo,545,449,https://www.1mg.com/otc/bare-anatomy-anti-dand...
14,Sensodyne Repair & Protect Sensitive Toothpaste,tube of 100 gm Toothpaste,270,252,https://www.1mg.com/otc/sensodyne-repair-prote...
15,Hamdard Safi Natural Blood Purifier Syrup | Fo...,bottle of 200 ml Syrup,None,120,https://www.1mg.com/otc/hamdard-safi-natural-b...
16,Bioderma Sebium Hydra Moisturiser | For Acne P...,tube of 40 ml Moisturiser,None,1195,https://www.1mg.com/otc/bioderma-sebium-hydra-...
17,Minimalist 18% Hair Growth Actives Hair Serum ...,bottle of 30 ml Serum,799,719,https://www.1mg.com/otc/minimalist-18-hair-gro...
18,Nivea Body Milk Nourishing Lotion,bottle of 120 ml Lotion,125,115,https://www.1mg.com/otc/nivea-body-milk-nouris...
19,Dettol Antiseptic Disinfectant Liquid,Canister of 5000 ml Liquid,2184.94,2032,https://www.1mg.com/otc/dettol-antiseptic-disi...
20,CeraVe Foaming Cleanser for Normal & Oily Skin,pump bottle of 473 ml Cleanser,1650,1568,https://www.1mg.com/otc/cerave-foaming-cleanse...
21,Little's Soft Cleansing Baby Wipes with Lid,packet of 80 wipes,220,99,https://www.1mg.com/otc/little-s-soft-cleansin...
22,Nivea 5 in 1 Complete Care Nourishing Lotion B...,pump bottle of 400 ml Lotion,520,380,https://www.1mg.com/otc/nivea-5-in-1-complete-...
23,Plum Rice Water & 10% Niacinamide Serum,bottle of 30 ml Serum,659,587,https://www.1mg.com/otc/plum-rice-water-10-nia...
24,Palmolive Aroma Absolute Relax Bodywash Shower...,bottle of 250 ml Body Wash,259,148,https://www.1mg.com/otc/palmolive-aroma-absolu...
25,Episoft AC Moisturiser with Microencapsulated ...,tube of 75 gm Cream,678,610,https://www.1mg.com/otc/episoft-ac-moisturiser...
26,Bare Anatomy Advanced Hair Growth Serum,bottle of 30 ml Serum,849,749,https://www.1mg.com/otc/bare-anatomy-advanced-...
27,Minimalist 10% Vitamin C Face Serum | Brighten...,bottle of 30 ml Serum,699,629,https://www.1mg.com/otc/minimalist-10-vitamin-...
28,Skore Timeless Climax Delay | Dotted & Ribbed ...,box of 10 condoms,180,105,https://www.1mg.com/otc/skore-timeless-climax-...
29,Fixderma Cosmetic Laboratories AHA Lightening ...,bottle of 30 ml Gel,None,1650,https://www.1mg.com/otc/fixderma-cosmetic-labo...
30,Mintop Shampoo for Hair Fall Control | Sulphat...,bottle of 100 ml Shampoo,544.5,425,https://www.1mg.com/otc/mintop-shampoo-for-hai...
31,mCaffeine Milky brew Face Scrub Remove Blackhe...,tube of 75 gm Scrub,None,229,https://www.1mg.com/otc/mcaffeine-milky-brew-f...
32,mCaffeine Naked & Raw Coffee Body Scrub | For ...,jar of 100 gm Scrub,None,449,https://www.1mg.com/otc/mcaffeine-naked-raw-co...
33,Protinex Diabetes Care Protein Powder with Vit...,box of 400 gm Powder,760,631,https://www.1mg.com/otc/protinex-diabetes-care...
34,VLCC Natural Science Fair + Glow Sun Scree Lot...,combo pack of 3 lotions,900,747,https://www.1mg.com/otc/vlcc-natural-science-f...
35,Natuur Moisturiser Lavender Chamomile,jar of 100 ml Moisturiser,400,360,https://www.1mg.com/otc/natuur-moisturiser-lav...
36,"Nivea Soft Light Moisturiser for Face, Body & ...",jar of 300 ml Cream,660,330,https://www.1mg.com/otc/nivea-soft-light-moist...
37,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,205,https://www.1mg.com/otc/bombay-shaving-company...
38,Oxyglow Herbals Papaya Bleach Cream,box of 300 gm Cream,310,217,https://www.1mg.com/otc/oxyglow-herbals-papaya...
39,VLCC Combo Pack of Diamond Single Facial Kit (...,combo pack of 2 units,548,525,https://www.1mg.com/otc/vlcc-combo-pack-of-dia...
40,Natuur Cedarwood & Ylang Ylang Body Mist,pump bottle of 100 ml Liquid,450,405,https://www.1mg.com/otc/natuur-cedarwood-ylang...
41,Khadi Mauri Herbal Tea Tree Shampoo (210ml Each),combo pack of 4 bottles,1180,944,https://www.1mg.com/otc/khadi-mauri-herbal-tea...
42,The Love Co. Body Lotion Oud Accord,bottle of 250 ml Lotion,799,659,https://www.1mg.com/otc/the-love-co.-body-loti...
43,Habibs Hair Serum (100ml Each),combo pack of 3 bottles,None,990,https://www.1mg.com/otc/habibs-hair-serum-100m...
44,Scruze Condom Extra Dotted Gear Up,box of 10 condoms,90,64.8,https://www.1mg.com/otc/scruze-condom-extra-do...
45,Sun Scoop Oil Control Gel Sunscreen SPF 50 PA++++,tube of 45 gm Cream,449,399,https://www.1mg.com/otc/sun-scoop-oil-control-...
46,Familio All In One Shampoo + Conditioner Shampoo,bottle of 200 ml Shampoo,699,664,https://www.1mg.com/otc/familio-all-in-one-sha...
47,Glutone Face Wash(100ml Each),tube of 4 Packs,1740,1496,https://www.1mg.com/otc/glutone-face-wash-100m...
48,Amrit Navjeevan Herbal Hair Oil (100ml Each),combo pack of 2 bottles,430,409,https://www.1mg.com/otc/amrit-navjeevan-herbal...
49,Daffy Baby Lotion,pump bottle of 200 ml Lotion,600,432,https://www.1mg.com/otc/daffy-baby-lotion-otc9...

In [7]:
df['MRPs']=df['MRPs'].fillna(df['selling_price'])
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Cetaphil Gentle Skin Cleanser | For Dry to Nor...,pump bottle of 1000 ml Cleanser,1679,1511,https://www.1mg.com/otc/cetaphil-gentle-skin-c...
1,Sensodyne Repair & Protect Sensitive Toothpaste,tube of 100 gm Toothpaste,270,252,https://www.1mg.com/otc/sensodyne-repair-prote...
2,Lacto Calamine Sunscreen | With Kaolin Clay & ...,tube of 50 gm Cream,399,219,https://www.1mg.com/otc/lacto-calamine-sunscre...
3,Sesderma Ocean Skin Nourishing Facial Cream,jar of 50 ml Cream,3300,3300,https://www.1mg.com/otc/sesderma-ocean-skin-no...
4,Rivela Lite Weightless Mousse Broad Spectrum U...,tube of 40 gm Cream,700,617,https://www.1mg.com/otc/rivela-lite-weightless...
...,...,...,...,...,...
23739,Beardhood Beard & Mustache Wax,jar of 30 gm Wax,400,289,https://www.1mg.com/otc/beardhood-beard-mustac...
23740,Pores Be Pure Skin Brightening & Exfoliating F...,tube of 100 gm Face Wash,299,179,https://www.1mg.com/otc/pores-be-pure-skin-bri...
23741,Himalaya Gentle Baby Wipes,packet of 72 wipes,280,263,https://www.1mg.com/otc/himalaya-gentle-baby-w...
23742,Beardhood Clean Look Face Wash,bottle of 100 ml Face Wash,299,253,https://www.1mg.com/otc/beardhood-clean-look-f...
23743,Chicco Teat Perfect 5 for Babies 6M+ 6m+,box of 1 Unit,319,306,https://www.1mg.com/otc/chicco-teat-perfect-5-...

In [8]:
df['type of product'] = df['size_of_bottle'].str.split(' ').str[-1]

In [9]:
df.head(50)

,name,size_of_bottle,MRPs,selling_price,1mg_url,type of product
0,Cetaphil Gentle Skin Cleanser | For Dry to Nor...,pump bottle of 1000 ml Cleanser,1679,1511,https://www.1mg.com/otc/cetaphil-gentle-skin-c...,Cleanser
1,Sensodyne Repair & Protect Sensitive Toothpaste,tube of 100 gm Toothpaste,270,252,https://www.1mg.com/otc/sensodyne-repair-prote...,Toothpaste
2,Lacto Calamine Sunscreen | With Kaolin Clay & ...,tube of 50 gm Cream,399,219,https://www.1mg.com/otc/lacto-calamine-sunscre...,Cream
3,Sesderma Ocean Skin Nourishing Facial Cream,jar of 50 ml Cream,3300,3300,https://www.1mg.com/otc/sesderma-ocean-skin-no...,Cream
4,Rivela Lite Weightless Mousse Broad Spectrum U...,tube of 40 gm Cream,700,617,https://www.1mg.com/otc/rivela-lite-weightless...,Cream
5,Cetaphil Oily Skin Cleanser | For Combination ...,bottle of 125 ml Cleanser,699,615,https://www.1mg.com/otc/cetaphil-oily-skin-cle...,Cleanser
6,Minimalist 10% Vitamin C Face Serum | Brighten...,bottle of 30 ml Serum,699,629,https://www.1mg.com/otc/minimalist-10-vitamin-...,Serum
7,Hamdard Safi Natural Blood Purifier Syrup | Fo...,bottle of 500 ml Syrup,250,228,https://www.1mg.com/otc/hamdard-safi-natural-b...,Syrup
8,CIR Adult Diaper Pants | 10 hr Absorption Prot...,packet of 10 diapers,499,233,https://www.1mg.com/otc/cir-adult-diaper-pants...,diapers
9,Sesderma Ocean skin Moisturising Serum,bottle of 30 ml Serum,2800,2800,https://www.1mg.com/otc/sesderma-ocean-skin-mo...,Serum
10,i-Know Ovulation Kit | Testing Strip Kit | Fir...,packet of 5 Test Kits,549,339,https://www.1mg.com/otc/i-know-ovulation-kit-t...,Kits
11,Cetaphil Baby Daily Lotion | Nourishes Skin,pump bottle of 400 ml Lotion,950,846,https://www.1mg.com/otc/cetaphil-baby-daily-lo...,Lotion
12,Minimalist 16% Vitamin C + E + Ferulic Acid Fa...,bottle of 20 ml Serum,599,539,https://www.1mg.com/otc/minimalist-16-vitamin-...,Serum
13,Bare Anatomy Anti-Dandruff Shampoo,bottle of 250 ml Shampoo,545,449,https://www.1mg.com/otc/bare-anatomy-anti-dand...,Shampoo
14,Sensodyne Repair & Protect Sensitive Toothpaste,tube of 100 gm Toothpaste,270,252,https://www.1mg.com/otc/sensodyne-repair-prote...,Toothpaste
15,Hamdard Safi Natural Blood Purifier Syrup | Fo...,bottle of 200 ml Syrup,120,120,https://www.1mg.com/otc/hamdard-safi-natural-b...,Syrup
16,Bioderma Sebium Hydra Moisturiser | For Acne P...,tube of 40 ml Moisturiser,1195,1195,https://www.1mg.com/otc/bioderma-sebium-hydra-...,Moisturiser
17,Minimalist 18% Hair Growth Actives Hair Serum ...,bottle of 30 ml Serum,799,719,https://www.1mg.com/otc/minimalist-18-hair-gro...,Serum
18,Nivea Body Milk Nourishing Lotion,bottle of 120 ml Lotion,125,115,https://www.1mg.com/otc/nivea-body-milk-nouris...,Lotion
19,Dettol Antiseptic Disinfectant Liquid,Canister of 5000 ml Liquid,2184.94,2032,https://www.1mg.com/otc/dettol-antiseptic-disi...,Liquid
20,CeraVe Foaming Cleanser for Normal & Oily Skin,pump bottle of 473 ml Cleanser,1650,1568,https://www.1mg.com/otc/cerave-foaming-cleanse...,Cleanser
21,Little's Soft Cleansing Baby Wipes with Lid,packet of 80 wipes,220,99,https://www.1mg.com/otc/little-s-soft-cleansin...,wipes
22,Nivea 5 in 1 Complete Care Nourishing Lotion B...,pump bottle of 400 ml Lotion,520,380,https://www.1mg.com/otc/nivea-5-in-1-complete-...,Lotion
23,Plum Rice Water & 10% Niacinamide Serum,bottle of 30 ml Serum,659,587,https://www.1mg.com/otc/plum-rice-water-10-nia...,Serum
24,Palmolive Aroma Absolute Relax Bodywash Shower...,bottle of 250 ml Body Wash,259,148,https://www.1mg.com/otc/palmolive-aroma-absolu...,Wash
25,Episoft AC Moisturiser with Microencapsulated ...,tube of 75 gm Cream,678,610,https://www.1mg.com/otc/episoft-ac-moisturiser...,Cream
26,Bare Anatomy Advanced Hair Growth Serum,bottle of 30 ml Serum,849,749,https://www.1mg.com/otc/bare-anatomy-advanced-...,Serum
27,Minimalist 10% Vitamin C Face Serum | Brighten...,bottle of 30 ml Serum,699,629,https://www.1mg.com/otc/minimalist-10-vitamin-...,Serum
28,Skore Timeless Climax Delay | Dotted & Ribbed ...,box of 10 condoms,180,105,https://www.1mg.com/otc/skore-timeless-climax-...,condoms
29,Fixderma Cosmetic Laboratories AHA Lightening ...,bottle of 30 ml Gel,1650,1650,https://www.1mg.com/otc/fixderma-cosmetic-labo...,Gel
30,Mintop Shampoo for Hair Fall Control | Sulphat...,bottle of 100 ml Shampoo,544.5,425,https://www.1mg.com/otc/mintop-shampoo-for-hai...,Shampoo
31,mCaffeine Milky brew Face Scrub Remove Blackhe...,tube of 75 gm Scrub,229,229,https://www.1mg.com/otc/mcaffeine-milky-brew-f...,Scrub
32,mCaffeine Naked & Raw Coffee Body Scrub | For ...,jar of 100 gm Scrub,449,449,https://www.1mg.com/otc/mcaffeine-naked-raw-co...,Scrub
33,Protinex Diabetes Care Protein Powder with Vit...,box of 400 gm Powder,760,631,https://www.1mg.com/otc/protinex-diabetes-care...,Powder
34,VLCC Natural Science Fair + Glow Sun Scree Lot...,combo pack of 3 lotions,900,747,https://www.1mg.com/otc/vlcc-natural-science-f...,lotions
35,Natuur Moisturiser Lavender Chamomile,jar of 100 ml Moisturiser,400,360,https://www.1mg.com/otc/natuur-moisturiser-lav...,Moisturiser
36,"Nivea Soft Light Moisturiser for Face, Body & ...",jar of 300 ml Cream,660,330,https://www.1mg.com/otc/nivea-soft-light-moist...,Cream
37,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,205,https://www.1mg.com/otc/bombay-shaving-company...,units
38,Oxyglow Herbals Papaya Bleach Cream,box of 300 gm Cream,310,217,https://www.1mg.com/otc/oxyglow-herbals-papaya...,Cream
39,VLCC Combo Pack of Diamond Single Facial Kit (...,combo pack of 2 units,548,525,https://www.1mg.com/otc/vlcc-combo-pack-of-dia...,units
40,Natuur Cedarwood & Ylang Ylang Body Mist,pump bottle of 100 ml Liquid,450,405,https://www.1mg.com/otc/natuur-cedarwood-ylang...,Liquid
41,Khadi Mauri Herbal Tea Tree Shampoo (210ml Each),combo pack of 4 bottles,1180,944,https://www.1mg.com/otc/khadi-mauri-herbal-tea...,bottles
42,The Love Co. Body Lotion Oud Accord,bottle of 250 ml Lotion,799,659,https://www.1mg.com/otc/the-love-co.-body-loti...,Lotion
43,Habibs Hair Serum (100ml Each),combo pack of 3 bottles,990,990,https://www.1mg.com/otc/habibs-hair-serum-100m...,bottles
44,Scruze Condom Extra Dotted Gear Up,box of 10 condoms,90,64.8,https://www.1mg.com/otc/scruze-condom-extra-do...,condoms
45,Sun Scoop Oil Control Gel Sunscreen SPF 50 PA++++,tube of 45 gm Cream,449,399,https://www.1mg.com/otc/sun-scoop-oil-control-...,Cream
46,Familio All In One Shampoo + Conditioner Shampoo,bottle of 200 ml Shampoo,699,664,https://www.1mg.com/otc/familio-all-in-one-sha...,Shampoo
47,Glutone Face Wash(100ml Each),tube of 4 Packs,1740,1496,https://www.1mg.com/otc/glutone-face-wash-100m...,Packs
48,Amrit Navjeevan Herbal Hair Oil (100ml Each),combo pack of 2 bottles,430,409,https://www.1mg.com/otc/amrit-navjeevan-herbal...,bottles
49,Daffy Baby Lotion,pump bottle of 200 ml Lotion,600,432,https://www.1mg.com/otc/daffy-baby-lotion-otc9...,Lotion

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23744 entries, 0 to 23743
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             23744 non-null  object
 1   size_of_bottle   23744 non-null  object
 2   MRPs             23744 non-null  object
 3   selling_price    23744 non-null  object
 4   1mg_url          23744 non-null  object
 5   type of product  23744 non-null  object
dtypes: object(6)
memory usage: 1.1+ MB

In [11]:
df['MRPs'] = pd.to_numeric(df['MRPs'], errors='coerce')
df['selling_price'] = pd.to_numeric(df['selling_price'], errors='coerce')

In [12]:
df.to_csv("C:\\Users\\MICILMEDS\\Documents\\Medi_final\\correct_data\\Category\\personal_Care.csv", index=False)  # Save the DataFrame to a CSV file